[project]
name = 'stackspay-pro'
description = 'StacksPay Pro contracts for USDCx payments'
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.usdcx'
[contracts.payment-requests]
path = 'contracts/payment-requests.clar'
clarity_version = 3
epoch = 'latest'

[contracts.username-registry]
path = 'contracts/username-registry.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
